import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import mistral from "@/lib/mistral";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// example
mistral.start().then(() => {
  mistral.shouldBeFlagged("<YOUR POST HERE>").then((res) => console.log(res))
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
